name: RotatingHeads2
author: [Gennario, siberanka]
version: 2.0
main: cz.gennario.newrotatingheads.Main
api-version: 1.13
folia-supported: true
softdepend:
  - PlaceholderAPI
  - Multiworld
  - Multiverse-Core
  - TransparentHeads
depend:
  - ProtocolLib
